# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SelectFiles
                                 A QGIS plugin
 Select all files with a given format in a directory.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-20
        copyright            : (C) 2020 by Piotr Koller
        email                : piotrkoller96@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SelectFiles class from file SelectFiles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .select_files import SelectFiles
    return SelectFiles(iface)
